name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      uses: vgaidarji/android-github-actions/build@v1.0.0
    - name: Android Tests
      uses: vgaidarji/android-github-actions/emulator@v1.0.0
